version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: DB
      POSTGRES_USER: User
      POSTGRES_PASSWORD: PASSWORD
      POSTGRES_HOST: 0.0.0.0
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-network

  my-node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - my-network

networks:
  my-network:

volumes:
  postgres_data:
